# Generated by Django 4.1.5 on 2023-01-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Providers',
        ),
    ]
